/*
Copyright KM_2023 Hannah Blythe Morrison

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#pragma once

#define TAPPING_TERM_PER_KEY

// Tapping terms.

#define TAPPING_TERM 190
#define TAPPING_TERM_MODS 900
#define TAPPING_TERM_LAYER 150
#define TAPPING_TERM_SIDEKEY_TD 150
#if defined TAP_DANCE_ENABLE && defined HBM_TD_HOLD_ORIGINAL_KEYPRESS_ENABLE
#define TAPPING_TERM_THUMBKEY_TD 30
#else // if ! TAP_DANCE_ENABLE && HBM_TD_HOLD_ORIGINAL_KEYPRESS_ENABLE
#define TAPPING_TERM_THUMBKEY_TD 150
#endif // TAP_DANCE_ENABLE && HBM_TD_HOLD_ORIGINAL_KEYPRESS_ENABLE

// Capsword.

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 10000 // ten seconds.

// Enable kinetic mouse for nice scroll wheel emulation.

#define MK_KINETIC_SPEED
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_DELAY 100
#define MOUSEKEY_WHEEL_DELAY 100

#define MOUSEKEY_WHEEL_INTERVAL 70 // The default is 100
#define MOUSEKEY_WHEEL_TIME_TO_MAX 80 // The default is 40

#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 12
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 32
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 32
#define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 12

// Filler for non-base layers so they match the base layer format, and test
// platform to fill in the blanks.

#ifdef FK_TOP_OUTER
#define SPACER_TL KC_NO,
#define SPACER_TR ,KC_NO
#define TEST_TL
#define TEST_TR
#else
#define SPACER_TL
#define SPACER_TR
#define TEST_TL KC_NO,
#define TEST_TR ,KC_NO
#endif

#ifdef FK_MDL_OUTER
#define SPACER_ML KC_NO,
#define SPACER_MR ,KC_NO
#define TEST_ML
#define TEST_MR
#else
#define SPACER_ML
#define SPACER_MR
#define TEST_ML KC_NO,
#define TEST_MR ,KC_NO
#endif

#ifdef FK_BTM_OUTER
#define SPACER_BL KC_NO,
#define SPACER_BR ,KC_NO
#define TEST_BL
#define TEST_BR
#else
#define SPACER_BL
#define SPACER_BR
#define TEST_BL KC_NO,
#define TEST_BR ,KC_NO
#endif

#ifdef FK_TOP_INNER
#define SPACER_TI KC_NO, KC_NO,
#define TEST_TI
#else
#define SPACER_TI
#define TEST_TI KC_NO, KC_NO,
#endif

#ifdef FK_MDL_INNER
#define SPACER_MI KC_NO, KC_NO,
#define TEST_MI
#else
#define SPACER_MI
#define TEST_MI KC_NO, KC_NO,
#endif

#ifdef FK_BTM_INNER
#define SPACER_BI KC_NO, KC_NO,
#define TEST_BI
#else
#define SPACER_BI
#define TEST_BI KC_NO, KC_NO,
#endif

#ifdef FK_THUMB_OUTER
#define TEST_THL
#define TEST_THR
#else
#define TEST_THL KC_NO,
#define TEST_THR ,KC_NO
#endif

// Reduce the size of the compiled firmware.

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_MUSIC_MODE
#define LAYER_STATE_8BIT

#undef RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_TWINKLE

#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_BREATHING
#undef ENABLE_RGB_MATRIX_BAND_SAT
#undef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#undef ENABLE_RGB_MATRIX_RAINDROPS
#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_HUE_BREATHING
#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef ENABLE_RGB_MATRIX_HUE_WAVE
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef ENABLE_RGB_MATRIX_SPLASH
#undef ENABLE_RGB_MATRIX_MULTISPLASH
#undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
