/*
Copyright KM_2023 Hannah Blythe Morrison

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef USERSPACE
#define USERSPACE

#include "quantum.h"

// Layers and layer aliases.

enum hbm_layers {
  LAYER_BASE,
  LAYER_SYM,
  LAYER_NAV,
  LAYER_NUM,
  LAYER_SCUT
};

#define LAYER_ENT_HOLD LAYER_NUM
#define LAYER_SPC_HOLD LAYER_NAV
#define LAYER_SLSH_TAP LAYER_SCUT
#define LAYER_SLSH_HOLD LAYER_NUM
#define LAYER_Z_TAP LAYER_SYM
#define LAYER_Z_HOLD LAYER_NAV

// Custom keycodes.

enum hbm_keycodes {
    M_ALT_TAB = SAFE_RANGE,
    M_APP1,
    M_APP2,
    M_APP3,
    M_APP4,
    M_APP5,
    M_1PASS,
    M_HIDE,
    M_MAX,
    M_CLOSE,
    M_NDESK,
    M_PDESK,
    M_XTAB,
    M_EMOJI,
    M_4RAND,
#ifdef TAP_DANCE_ENABLE
    M_CW_TOGG,
#endif // TAP_DANCE_ENABLE
    M_ISCROS,
    M_ISWIN
};

// Tap dance keys.

enum {
  TD_ENT_LAYER,
  TD_SPC_LAYER,
  TD_SLSH_LAYER,
  TD_Z_LAYER
};

// Alternative keys for UK ISO keyboard layouts.

#define KC_UK_DQUO LSFT(KC_2)
#define KC_UK_PND LSFT(KC_3)
#define KC_UK_PIPE LSFT(KC_NUBS)
#define KC_UK_BSLS KC_NUBS
#define KC_UK_AT LSFT(KC_QUOT)
#define KC_UK_TILDE LSFT(KC_BSLS)
#define KC_UK_HASH KC_BSLS

// Modified keys.

#define KC_CTL_X LCTL(KC_X)
#define KC_CTL_C LCTL(KC_C)
#define KC_SFT_CTL_C LSFT(LCTL(KC_C))
#define KC_CTL_V LCTL(KC_V)
#define KC_CTL_TAB LCTL(KC_TAB)

// Homerow modifier keys.

#ifdef HBM_HOMEROW_ENABLE
#define KC_X_CTL LCTL_T(KC_X)
#define KC_C_ALT LALT_T(KC_C)
#define KC_D_GUI LGUI_T(KC_D)
#define KC_H_GUI LGUI_T(KC_H)
#define KC_COMM_ALT LALT_T(KC_COMM)
#define KC_DOT_CTL LCTL_T(KC_DOT)
#else // ! HBM_HOMEROW_ENABLE
#define KC_X_CTL KC_X
#define KC_C_ALT KC_C
#define KC_D_GUI KC_D
#define KC_H_GUI KC_H
#define KC_COMM_ALT KC_COMM
#define KC_DOT_CTL KC_DOT
#endif // HBM_HOMEROW_ENABLE

// Oneshot keys.

#define KC_OS_SFT OSM(MOD_LSFT)
#define KC_OS_CTL OSM(MOD_LCTL)
#define KC_OS_ALT OSM(MOD_LALT)
#define KC_OS_GUI OSM(MOD_LGUI)
#define KC_OS_SYM OSL(LAYER_SYM)
#define KC_OS_SCUT OSL(LAYER_SCUT)

// Optionally enable thumbkey layer keys.

#ifndef HBM_THUMBKEY_ENABLE
#define KC_SPC_LAYER KC_SPC
#define KC_ENT_LAYER KC_ENT
#else // HBM_THUMBKEY_ENABLE
#ifdef TAP_DANCE_ENABLE
#define KC_SPC_LAYER TD(TD_SPC_LAYER)
#define KC_ENT_LAYER TD(TD_ENT_LAYER)
#else
#define KC_SPC_LAYER LT(LAYER_SPC_HOLD, KC_SPC)
#define KC_ENT_LAYER LT(LAYER_ENT_HOLD, KC_ENT)
#endif // TAP_DANCE_ENABLE
#endif // HBM_THUMBKEY_ENABLE

// Optionally enable sidekey layer keys.

#ifndef HBM_SIDEKEY_ENABLE
#define KC_Z_LAYER KC_Z
#define KC_SLSH_LAYER KC_SLSH
#else // HBM_SIDEKEY_ENABLE
#ifdef TAP_DANCE_ENABLE
#define KC_Z_LAYER TD(TD_Z_LAYER)
#define KC_SLSH_LAYER TD(TD_SLSH_LAYER)
#else // ! TAP_DANCE_ENABLE
#define KC_Z_LAYER OSL(LAYER_Z_TAP)
#define KC_SLSH_LAYER OSL(LAYER_SLSH_TAP)
#endif // TAP_DANCE_ENABLE
#endif // HBM_SIDEKEY_ENABLE

#if defined HBM_THUMBKEY_ENABLE || defined HBM_SIDEKEY_ENABLE
#define KC_SYM_Z_LAYER KC_Z
#define KC_SYM_SLSH_LAYER KC_SLSH
#else // ! defined HBM_THUMBKEY_ENABLE || defined HBM_SIDEKEY_ENABLE
#define KC_SYM_Z_LAYER MO(LAYER_Z_HOLD)
#define KC_SYM_SLSH_LAYER MO(LAYER_SLSH_HOLD)
#endif // defined HBM_THUMBKEY_ENABLE || defined HBM_SIDEKEY_ENABLE

// Define CW_TOGG as a macro so that layer hold tap dances see the keypress and
// fall into the HOLD_KEYPRESS state properly.

#ifdef TAP_DANCE_ENABLE
#define KC_CW_TOGG M_CW_TOGG
#else // ! TAP_DANCE_ENABLE
#define KC_CW_TOGG CW_TOGG
#endif // TAP_DANCE_ENABLE

// Replace mousewheel scroll keys with page up and down if mouse keys is not
// enabled.

#ifdef MOUSEKEY_ENABLE
#define KC_SCROLL_UP KC_MS_WH_UP
#define KC_SCROLL_DN KC_MS_WH_DOWN
#else // ! MOUSEKEY_ENABLE
#define KC_SCROLL_UP KC_PAGE_UP
#define KC_SCROLL_DN KC_PAGE_DOWN
#endif // MOUSEKEY_ENABLE

// Layouts.

#define HBM_LAYOUT_split_3x5_2(...) LAYOUT_split_3x5_2(__VA_ARGS__)
#define HBM_LAYOUT_planck_grid(...) LAYOUT_planck_grid(__VA_ARGS__)

// Base layer.

#define KM_5_BASE_1L KC_Q, KC_W, KC_F, KC_P, KC_B
#define KM_5_BASE_2L KC_A, KC_R, KC_S, KC_T, KC_G
#define KM_5_BASE_3L KC_Z_LAYER, KC_X_CTL, KC_C_ALT, KC_D_GUI, KC_V

#define KM_5_BASE_1R KC_J, KC_L, KC_U, KC_Y, KC_BSPC
#define KM_5_BASE_2R KC_M, KC_N, KC_E, KC_I, KC_O
#define KM_5_BASE_3R KC_K, KC_H_GUI, KC_COMM_ALT, KC_DOT_CTL, KC_SLSH_LAYER

#define KM_5_BASE_1 KM_5_BASE_1L, KM_5_BASE_1R
#define KM_5_BASE_2 KM_5_BASE_2L, KM_5_BASE_2R
#define KM_5_BASE_3 KM_5_BASE_3L, KM_5_BASE_3R

#define KM_6_BASE_1R KC_J, KC_L, KC_U, KC_Y, KC_DEL, KC_BSPC

#define KM_6_BASE_1 KC_ESC, KM_5_BASE_1L, KM_6_BASE_1R
#define KM_6_BASE_2 KC_TAB, KM_5_BASE_2L, KM_5_BASE_2R, KC_UK_BSLS
#define KM_6_BASE_3 KC_OS_SYM, KM_5_BASE_3L, KM_5_BASE_3R, KC_OS_SCUT

#define KM_2THUMB_BASE_L KC_OS_SFT, KC_SPC_LAYER
#define KM_2THUMB_BASE_R KC_ENT_LAYER, KC_OS_SYM

#define KM_2THUMB_BASE KM_2THUMB_BASE_L, KM_2THUMB_BASE_R

#define KM_3THUMB_BASE_L KC_OS_SFT, KC_SPC_LAYER, KC_TAB
#define KM_3THUMB_BASE_R KC_ESC, KC_ENT_LAYER, KC_OS_SYM

#define KM_3THUMB_BASE KM_3THUMB_BASE_L, KM_3THUMB_BASE_R

#define KM_12_BASE_4L KC_OS_SFT, KC_OS_CTL, KC_OS_ALT, KC_OS_GUI, KM_2THUMB_BASE_L
#define KM_12_BASE_4R KM_2THUMB_BASE_R, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT

#define KM_12_BASE_4 KM_12_BASE_4L, KM_12_BASE_4R

#define HBM_LAYOUT_3x5_2_BASE KM_5_BASE_1, KM_5_BASE_2, KM_5_BASE_3, KM_2THUMB_BASE
#define HBM_LAYOUT_3x6_3_BASE KM_6_BASE_1, KM_6_BASE_2, KM_6_BASE_3, KM_3THUMB_BASE
#define HBM_LAYOUT_4x12_BASE KM_6_BASE_1, KM_6_BASE_2, KM_6_BASE_3, KM_12_BASE_4

// Symbol layer.

#define KM_5_SYM_1L KC_EXLM, KC_UK_DQUO, KC_UK_PND, KC_DLR, KC_PERC
#define KM_5_SYM_2L KC_GRV, KC_UK_PIPE, KC_LBRC, KC_LCBR, KC_LPRN
#define KM_5_SYM_3L KC_SYM_Z_LAYER, KC_UK_BSLS, KC_RBRC, KC_RCBR, KC_RPRN

#define KM_5_SYM_1R KC_CIRC, KC_AMPR, KC_ASTR, KC_UNDS, KC_PLUS
#define KM_5_SYM_2R KC_COLN, KC_UK_AT, KC_UK_TILDE, KC_MINS, KC_EQL
#define KM_5_SYM_3R KC_SCLN, KC_QUOT, KC_UK_HASH, KC_GT, KC_SYM_SLSH_LAYER

#define KM_5_SYM_1 KM_5_SYM_1L, KM_5_SYM_1R
#define KM_5_SYM_2 KM_5_SYM_2L, KM_5_SYM_2R
#define KM_5_SYM_3 KM_5_SYM_3L, KM_5_SYM_3R

#define KM_6_SYM_1 KC_TRNS, KM_5_SYM_1L, KM_5_SYM_1R, KC_TRNS
#define KM_6_SYM_2 KC_TRNS, KM_5_SYM_2L, KM_5_SYM_2R, KC_TRNS
#define KM_6_SYM_3 KC_TRNS, KM_5_SYM_3L, KM_5_SYM_3R, KC_TRNS

#define KM_2THUMB_SYM_L KC_ESC, KC_TAB
#define KM_2THUMB_SYM_R KC_NO, KC_OS_SCUT

#define KM_2THUMB_SYM KM_2THUMB_SYM_L, KM_2THUMB_SYM_R

#define KM_3THUMB_SYM_L KM_2THUMB_SYM_L, KC_TRNS
#define KM_3THUMB_SYM_R KC_TRNS, KM_2THUMB_SYM_R

#define KM_3THUMB_SYM KM_3THUMB_SYM_L, KM_3THUMB_SYM_R

#define KM_12_SYM_4L KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KM_2THUMB_SYM_L
#define KM_12_SYM_4R KM_2THUMB_SYM_R, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

#define KM_12_SYM_4 KM_12_SYM_4L, KM_12_SYM_4R

#define HBM_LAYOUT_3x5_2_SYM KM_5_SYM_1, KM_5_SYM_2, KM_5_SYM_3, KM_2THUMB_SYM
#define HBM_LAYOUT_3x6_3_SYM KM_6_SYM_1, KM_6_SYM_2, KM_6_SYM_3, KM_3THUMB_SYM
#define HBM_LAYOUT_4x12_SYM KM_6_SYM_1, KM_6_SYM_2, KM_6_SYM_3, KM_12_SYM_4

// Navigation layer.

#define KM_5_NAV_1L KC_PSCR, KC_MNXT, KC_MPLY, KC_VOLU, KC_BRIU
#define KM_5_NAV_2L KC_NO, KC_MPRV, KC_MUTE, KC_VOLD, KC_BRID
#define KM_5_NAV_3L KC_NO, KC_CTL_X, KC_CTL_C, KC_SFT_CTL_C, KC_CTL_V

#define KM_5_NAV_1R KC_NO, M_PDESK, KC_CTL_TAB, M_ALT_TAB, M_NDESK
#define KM_5_NAV_2R KC_SCROLL_UP, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT
#define KM_5_NAV_3R KC_SCROLL_DN, KC_HOME, KC_PGDN, KC_PGUP, KC_END

#define KM_5_NAV_1 KM_5_NAV_1L, KM_5_NAV_1R
#define KM_5_NAV_2 KM_5_NAV_2L, KM_5_NAV_2R
#define KM_5_NAV_3 KM_5_NAV_3L, KM_5_NAV_3R

#define KM_6_NAV_1 KC_TRNS, KM_5_NAV_1L, KM_5_NAV_1R, KC_TRNS
#define KM_6_NAV_2 KC_TRNS, KM_5_NAV_2L, KM_5_NAV_2R, KC_TRNS
#define KM_6_NAV_3 KC_TRNS, KM_5_NAV_3L, KM_5_NAV_3R, KC_TRNS

#define KM_2THUMB_NAV_L KC_TRNS, KC_TRNS
#define KM_2THUMB_NAV_R KC_ESC, KC_OS_SCUT

#define KM_2THUMB_NAV KM_2THUMB_NAV_L, KM_2THUMB_NAV_R

#define KM_3THUMB_NAV_L KM_2THUMB_NAV_L, KC_TRNS
#define KM_3THUMB_NAV_R KC_TRNS, KM_2THUMB_NAV_R

#define KM_3THUMB_NAV KM_3THUMB_NAV_L, KM_3THUMB_NAV_R

#define KM_12_NAV_4L KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KM_2THUMB_NAV_L
#define KM_12_NAV_4R KM_2THUMB_NAV_R, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

#define KM_12_NAV_4 KM_12_NAV_4L, KM_12_NAV_4R

#define HBM_LAYOUT_3x5_2_NAV KM_5_NAV_1, KM_5_NAV_2, KM_5_NAV_3, KM_2THUMB_NAV
#define HBM_LAYOUT_3x6_3_NAV KM_6_NAV_1, KM_6_NAV_2, KM_6_NAV_3, KM_3THUMB_NAV
#define HBM_LAYOUT_4x12_NAV KM_6_NAV_1, KM_6_NAV_2, KM_6_NAV_3, KM_12_NAV_4

// Number layer.

#define KM_5_NUM_1L KC_PAST, KC_1, KC_2, KC_3, KC_PPLS
#define KM_5_NUM_2L KC_PSLS, KC_4, KC_5, KC_6, KC_PMNS
#define KM_5_NUM_3L KC_0, KC_7, KC_8, KC_9, KC_DOT

#define KM_5_NUM_1R KC_NO, KC_F1, KC_F2, KC_F3, KC_BSPC
#define KM_5_NUM_2R KC_NO, KC_F4, KC_F5, KC_F6, KC_NO
#define KM_5_NUM_3R KC_F10, KC_F7, KC_F8, KC_F9, KC_NO

#define KM_5_NUM_1 KM_5_NUM_1L, KM_5_NUM_1R
#define KM_5_NUM_2 KM_5_NUM_2L, KM_5_NUM_2R
#define KM_5_NUM_3 KM_5_NUM_3L, KM_5_NUM_3R

#define KM_6_NUM_1 KC_TRNS, KM_5_NUM_1L, KM_5_NUM_1R, KC_TRNS
#define KM_6_NUM_2 KC_TRNS, KM_5_NUM_2L, KM_5_NUM_2R, KC_TRNS
#define KM_6_NUM_3 KC_TRNS, KM_5_NUM_3L, KM_5_NUM_3R, KC_TRNS

#define KM_2THUMB_NUM_L KC_CW_TOGG, KC_TAB
#define KM_2THUMB_NUM_R KC_TRNS, KC_TRNS

#define KM_2THUMB_NUM KM_2THUMB_NUM_L, KM_2THUMB_NUM_R

#define KM_3THUMB_NUM_L KM_2THUMB_NUM_L, KC_TRNS
#define KM_3THUMB_NUM_R KC_TRNS, KM_2THUMB_NUM_R

#define KM_3THUMB_NUM KM_3THUMB_NUM_L, KM_3THUMB_NUM_R

#define KM_12_NUM_4L KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KM_2THUMB_NUM_L
#define KM_12_NUM_4R KM_2THUMB_NUM_R, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

#define KM_12_NUM_4 KM_12_NUM_4L, KM_12_NUM_4R

#define HBM_LAYOUT_3x5_2_NUM KM_5_NUM_1, KM_5_NUM_2, KM_5_NUM_3, KM_2THUMB_NUM
#define HBM_LAYOUT_3x6_3_NUM KM_6_NUM_1, KM_6_NUM_2, KM_6_NUM_3, KM_3THUMB_NUM
#define HBM_LAYOUT_4x12_NUM KM_6_NUM_1, KM_6_NUM_2, KM_6_NUM_3, KM_12_NUM_4

// Shortcut layer.

#define KM_5_SCUT_1L KC_NO, M_4RAND, KC_NO, KC_NO, KC_NO
#define KM_5_SCUT_2L M_APP1, M_APP2, M_APP3, M_APP4, M_APP5
#define KM_5_SCUT_3L KC_CAPS, KC_NO, KC_NO, M_1PASS, KC_NO

#define KM_5_SCUT_1R KC_NO, M_HIDE, M_MAX, M_CLOSE, M_ISCROS
#define KM_5_SCUT_2R KC_NO, KC_NO, M_EMOJI, KC_NO, M_ISWIN
#define KM_5_SCUT_3R KC_NO, KC_NO, KC_NO, KC_NO, KC_SLSH

#define KM_5_SCUT_1 KM_5_SCUT_1L, KM_5_SCUT_1R
#define KM_5_SCUT_2 KM_5_SCUT_2L, KM_5_SCUT_2R
#define KM_5_SCUT_3 KM_5_SCUT_3L, KM_5_SCUT_3R

#define KM_6_SCUT_1 KC_TRNS, KM_5_SCUT_1L, KM_5_SCUT_1R, KC_TRNS
#define KM_6_SCUT_2 KC_TRNS, KM_5_SCUT_2L, KM_5_SCUT_2R, KC_TRNS
#define KM_6_SCUT_3 KC_TRNS, KM_5_SCUT_3L, KM_5_SCUT_3R, KC_TRNS

#define KM_2THUMB_SCUT_L KC_ESC, KC_TAB
#define KM_2THUMB_SCUT_R KC_TRNS, KC_NO

#define KM_2THUMB_SCUT KM_2THUMB_SCUT_L, KM_2THUMB_SCUT_R

#define KM_3THUMB_SCUT_L KM_2THUMB_SCUT_L, KC_TRNS
#define KM_3THUMB_SCUT_R KC_TRNS, KM_2THUMB_SCUT_R

#define KM_3THUMB_SCUT KM_3THUMB_SCUT_L, KM_3THUMB_SCUT_R

#define KM_12_SCUT_4L KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KM_2THUMB_SCUT_L
#define KM_12_SCUT_4R KM_2THUMB_SCUT_R, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

#define KM_12_SCUT_4 KM_12_SCUT_4L, KM_12_SCUT_4R

#define HBM_LAYOUT_3x5_2_SCUT KM_5_SCUT_1, KM_5_SCUT_2, KM_5_SCUT_3, KM_2THUMB_SCUT
#define HBM_LAYOUT_3x6_3_SCUT KM_6_SCUT_1, KM_6_SCUT_2, KM_6_SCUT_3, KM_3THUMB_SCUT
#define HBM_LAYOUT_4x12_SCUT KM_6_SCUT_1, KM_6_SCUT_2, KM_6_SCUT_3, KM_12_SCUT_4

#endif // USERSPACE
