USER_NAME := hbmorrison
SRC += hbmorrison.c

MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes

HBM_THUMBKEY_ENABLE = yes
HBM_SIDEKEY_ENABLE = no
HBM_HOMEROW_ENABLE = yes
HBM_TD_HOLD_ORIGINAL_KEYPRESS_ENABLE = yes
